In [0]:
import pandas as pd
import datetime
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import seaborn as sns; sns.set(style="white", color_codes=True)

In [0]:
# create dataframes for three datasets
df_incidents = pd.read_pickle("incident_data.pkl")
df_holidays = pd.read_pickle("holidays_data.pkl")
df_weather = pd.read_pickle("weather_data.pkl")

In [0]:
# merge incident and weather datasets on Date and Time of Day
df = pd.merge(df_incidents, df_weather, on=['Date', 'TimeOfDay'])

In [0]:
# rearrange columns
df = df[['Date', 'Month', 'DayOfWeek', 'TimeOfDay', 'Arrond',
         'Temp', 'RelHum', 'Pressure', 'WindSpd',
         'TotalPrecip', 'CumulPrecip', 'SnowOnGrnd', 'WindPwr', 'NumUnits']]
df.head()

,Date,Month,DayOfWeek,TimeOfDay,Arrond,Temp,RelHum,Pressure,WindSpd,TotalPrecip,CumulPrecip,SnowOnGrnd,WindPwr,NumUnits
0,2015-01-03,1,5,3,38,0.253699,0.818359,0.694266,0.359043,0.166667,0.126645,0.235473,0.047374,1.0
1,2015-01-03,1,5,3,33,0.253699,0.818359,0.694266,0.359043,0.166667,0.126645,0.235473,0.047374,4.0
2,2015-01-03,1,5,3,43,0.253699,0.818359,0.694266,0.359043,0.166667,0.126645,0.235473,0.047374,1.0
3,2015-01-03,1,5,3,43,0.253699,0.818359,0.694266,0.359043,0.166667,0.126645,0.235473,0.047374,1.0
4,2015-01-03,1,5,3,27,0.253699,0.818359,0.694266,0.359043,0.166667,0.126645,0.235473,0.047374,5.0

In [0]:
df_holidays.head()

           Date  Holiday  TimeOfDay
0    2005-01-01        1          0
181  2005-01-01        1          1
543  2005-01-01        1          3
724  2005-01-02        1          0
1    2005-01-03        1          0

In [0]:
# merge holiday data
df = pd.merge(df, df_holidays, how='left', left_on=['Date', 'TimeOfDay'], right_on=['Date','TimeOfDay'])
# set 'Holiday' to 0 if not a holiday
df = df.fillna(0)

In [0]:
# set datat types
df = df.astype({"Holiday": int})
df = df.astype({"NumUnits": int})

In [0]:
df.head()

,Date,Month,DayOfWeek,TimeOfDay,Arrond,Temp,RelHum,Pressure,WindSpd,TotalPrecip,CumulPrecip,SnowOnGrnd,WindPwr,NumUnits,Holiday
0,2015-01-03,1,5,3,38,0.253699,0.818359,0.694266,0.359043,0.166667,0.126645,0.235473,0.047374,1,0
1,2015-01-03,1,5,3,33,0.253699,0.818359,0.694266,0.359043,0.166667,0.126645,0.235473,0.047374,4,0
2,2015-01-03,1,5,3,43,0.253699,0.818359,0.694266,0.359043,0.166667,0.126645,0.235473,0.047374,1,0
3,2015-01-03,1,5,3,43,0.253699,0.818359,0.694266,0.359043,0.166667,0.126645,0.235473,0.047374,1,0
4,2015-01-03,1,5,3,27,0.253699,0.818359,0.694266,0.359043,0.166667,0.126645,0.235473,0.047374,5,0

In [0]:
df =  df.groupby(['Arrond', 'Month', 'DayOfWeek', 'TimeOfDay', 
             'Temp', 'RelHum', 'Pressure', 'WindSpd', 'TotalPrecip', 'CumulPrecip',
             'SnowOnGrnd', 'WindPwr', 'Holiday']).size().rename('count').reset_index()

In [0]:
df.head()

,Arrond,Month,DayOfWeek,TimeOfDay,Temp,RelHum,Pressure,WindSpd,TotalPrecip,CumulPrecip,SnowOnGrnd,WindPwr,Holiday,count
0,0,1,0,0,0.001918,0.468750,0.784973,0.143617,0.000000,0.021382,0.170213,0.003239,0,3
1,0,1,0,0,0.053973,0.605469,0.751359,0.175532,0.000000,0.041118,0.382979,0.005827,1,5
2,0,1,0,0,0.076986,0.785156,0.997034,0.146277,0.000000,0.316612,0.553191,0.003407,0,2
3,0,1,0,0,0.090685,0.550781,0.765942,0.119681,0.000000,0.019737,0.340426,0.001832,0,3
4,0,1,0,0,0.108493,0.695312,0.501730,0.265957,0.014905,0.097862,0.361702,0.019673,0,4

In [0]:
# write dataframe to file
df.to_pickle('incident_plus_weather.pkl')